fichaube/alumnos/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

app_name = 'alumnos'

urlpatterns = [
    path('crear_alumno/', views.crear_alumno, name="crear_alumno"),
    path('borrar_alumno/<int:id_alumno>', views.borrarAlumno, name="borrarAlumno"),
    path('actualizar_alumno/<int:id_alumno>', views.updateAlumno, name="updateAlumno"),
    path('ver_alumno/<int:id_alumno>', views.verAlumno, name="verAlumno"),
    path('listar_alumnos/', views.listarAlumnos, name="listarAlumnos"),
    path('buscar_alumnos/', views.buscarAlumno, name="buscarAlumno"),
    path('import_alumnos/', views.importAlumnos, name="importAlumnos"),
]

fichaube/areas/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, re_path
from . import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
import areas.views

app_name = 'areas'
    # nota de pancho, esto del app_name es MUY importante!

urlpatterns = [

    # html's, estos despues se eliminaran*************
    path('agregar_Area', views.testpancho01, name="agregar_Area"),
    path('editar_Area/<int:idArea>', views.testpancho02, name='editar_Area'),
    path('agregar_Especialidad', views.testpancho03, name="agregar_Especialidad"),
    path('editar_Especialidad/<int:idEspecialidad>/<int:idArea>', views.testpancho04, name="editar_Especialidad"),

    # controladores de Areas
    path('agregarArea', views.agregarArea, name="agregarArea"),
    path('ajax/validarArea', views.validarArea, name="validarArea"),
    path('lista_Areas', views.listarAreas, name="lista_Areas"),
    path('eliminarArea/<int:idArea>', views.eliminarArea, name="eliminarArea"),
    path('editarArea', views.editarArea, name="editarArea"),
    path('editar_Area/ajax/validarArea', views.validarArea, name="validarArea"), # esta URL deberia eliminarla, y aprovechar la de mas arriba usando regex !!!

    # controladores de Especialidades
    path('lista_Especialidades/<int:idArea>', views.listarEspecialidades, name="lista_Especialidades"),
    path('agregarEspecialidad', views.agregarEspecialidad, name="agregarEspecialidad"),
    path('ajax/validarEspecialidad', views.validarEspecialidad, name="validarEspecialidad"),
    path('eliminarEspecialidad/<int:idEspecialidad>/<int:idArea>', views.eliminarEspecialidad, name="eliminarEspecialidad"),
    path('editarEspecialidad', views.editarEspecialidad, name="editarEspecialidad"),
    re_path(r'^editar_Especialidad/[0-9]+/ajax/validarEspecialidad', views.validarEspecialidad, name="validarEspecialidad")
]

fichaube/fichas/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from .views import GeneratePdf
from .views import ReporteExcel

app_name = 'fichas'

urlpatterns = [
    path('crear_ficha/', views.crearFicha, name="crearFicha"),
    path('confirmacion_ficha/<int:id_alumno>', views.confirmarCreacionFicha, name="confirmarCreacionFicha"),
    path('crear_registro/<int:id_alumno>', views.crearRegistro, name="crearRegistro"),
    path('reportes/', views.reportes, name="reportes"),
    path('generarReporte', ReporteExcel.as_view(), name="generarReporte"),
    path('crear_pdf_ficha/<int:id_alumno>', GeneratePdf.as_view(), name="crearFichaPDF"),
    path('ver_registro/<int:id_registro>', views.verRegistro, name="verRegistro"),
]

fichaube/fichaube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('areas/', include('areas.urls')),
    path('fichaube/', include('main.urls')),
    path('coordinador/', include('coordinador.urls')),
    path('profesional/', include('profesional.urls')),
    path('administrativo/', include('administrativo.urls')),
    path('mantenedor/', include('mantenedor.urls')),
    path('alumnos/', include('alumnos.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('fichas/', include('fichas.urls')),
    path('permisos/', include('permisos.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

fichaube/main/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, re_path
from . import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
import areas.views

urlpatterns = [
    path('home/', views.index, name='home'),
    path('login/', auth_views.LoginView.as_view(), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),

    # HANDLERS
    path('404/', views.handler404, name="404"),
    path('500/', views.handler500, name="500"),

    path('force_cambiar_pass/', views.force_cambiar_pass, name="force_cambiar_pass"),


]

fichaube/permisos/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

app_name = 'permisos'

urlpatterns = [
    path('ceder_permiso/<int:id_alumno>', views.cederPermiso, name="cederPermiso"),
    path('revocar_permiso/<int:id_permiso>/<int:id_alumno>', views.revocarPermiso, name="revocarPermiso"),
]

fichaube/main/models.py
from django.db import models

# Create your models here.

fichaube/main/views.py
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import get_object_or_404, render
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth import authenticate
from datetime import date, datetime, time
import logging
from django.urls import reverse
from django.template import *
from django.db.models import Q
from django.db.models import F
from django.contrib.auth.models import User
from django.contrib.auth.admin import UserAdmin
from usuarios.models import Usuario

# Create your views here.

#-----------------------------------------------------------FUNCIONES GENERALES!

#############---------FUNCION INDEX (HOME)------#################

@login_required()
def index(request):

    user = request.user
    if user.is_superuser:
        return render(request, 'home.html')

    usuario = Usuario.objects.get(user=user)

    #date_joined = datetime.combine(user.date_joined.date(), time(user.date_joined.hour, user.date_joined.minute))
    #last_login = datetime.combine(user.last_login.date(), time(user.last_login.hour, user.last_login.minute))
    #print (last_login)
    #print(date_joined)

    if usuario.has_previously_logged_in:
        return render(request, 'home.html')
    else:
        messages.warning(request, 'Por seguridad, por favor cambie su contraseña.')
        return HttpResponseRedirect(reverse("force_cambiar_pass"))



##############-----FUNCIONES HANDLERS 404 500-----####################

def handler404(request):
    return render(request, '404.html', status=404)

def handler500(request):
    return render(request, '500.html', status=500)


##############---------FUNCION DE CAMBIO PASSWORD----------####################


@login_required()
def force_cambiar_pass(request):
    template = "force_cambiar_pass.html"

    if request.method == 'GET':
        return render(request, template)

    if request.method == 'POST':
        try:
            usuario = Usuario.objects.get(user=request.user)
            passVieja = usuario.rut.split("-")[0][-4:]
            passNueva = request.POST.get('inputPassNueva')
            passConfirmacion = request.POST.get('inputPassConfirmada')
            print(passVieja, passNueva, passConfirmacion)
            user = authenticate(username=request.user.username, password=passVieja)

            if user is not None:
                if passNueva == passConfirmacion:
                    user.set_password(passNueva)
                    user.save()
                    update_session_auth_hash(request, user)
                    usuario.has_previously_logged_in = True
                    usuario.save()
                    print(usuario.nombre)
                    messages.success(request, '¡Contraseña cambiada con éxito!')
                else:
                    messages.error(request,'Las contraseñas no coinciden')
                    return HttpResponseRedirect(reverse("force_cambiar_pass"))
            else:
                messages.error(request,'La contraseña no es la correcta')
                return HttpResponseRedirect(reverse("force_cambiar_pass"))

        except Exception as e:
            messages.error(request,"No es posible cambiar contraseña. "+repr(e))
            return HttpResponseRedirect(reverse("force_cambiar_pass"))

        return HttpResponseRedirect(reverse("home"))

fichaube/main/templates/actualizar_alumno.html
{% extends 'home.html' %}


{% block content %}

<div class="col-sm-12 col-sm-offset-1">
  <div class="header text-center">
    <h2>Editar Estudiante</h2>
  </div>
</div>

{% if messages %}
{% for message in messages %}
{% if  message.tags == "error" %}
<div class="alert alert-danger" role="alert">
  {% else %}
  <div class="alert alert-success" role="alert">
    {% endif %}
    {{message}}
  </div>
  {% endfor %}
  {% endif %}

  <div class="col-sm-12 col-sm-offset-1">
    <div class="card">
      <div class="card-content">

        <div class="cuadro-form">

          <form method="POST" name="menuForm">
            {% csrf_token %}

            <div class="form-group row" name="groupRut" id="groupRut">
              <label for="inputRut" class="col-sm-3 col-form-label">Rut/Pasaporte:</label>
              <div class="col-sm-7">
                <input disabled type="text" class="form-control" id="inputRut" name="inputRut" value="{{ alumno.rut }}" autofocus>
              </div>
              <small class="text-info" id="msgRut"></small>
            </div>


            </br>


            <div class="form-group row">
              <label for="inputNombre" class="col-sm-2 col-form-label">Nombres:</label>
              <div class="col-sm-6">
                <input type="text" class="form-control" id="inputNombre" name="inputNombre" value="{{ alumno.nombre }}" required>
              </div>
            </div>


            <div class="form-group row">
              <label for="inputNombre" class="col-sm-2 col-form-label">Apellidos:</label>
              <div class="col-sm-5">
                <input type="text" class="form-control" id="inputApellidoPaterno" name="inputApellidoPaterno" value="{{ alumno.apellido_paterno }}" required>
              </div>
              <div class="col-sm-5">
                <input type="text" class="form-control" id="inputApellidoMaterno" name="inputApellidoMaterno" value="{{ alumno.apellido_materno }}" required>
              </div>
            </div>


            </br>


            <div class="form-group row">
              <label for="inputCorreo" class="col-sm-2 col-form-label">Correo:</label>
              <div class="col-sm-8">
                <input type="email" class="form-control" id="inputCorreo" name="inputCorreo" value="{{ alumno.correo }}" required>
              </div>
            </div>



            </br>



            <div class="form-group row">
              <label for="inputDomicilio" class="col-sm-2 col-form-label">Domicilio:</label>
              <div class="col-sm-8">
                <input type="text" class="form-control" id="inputDomicilio" name="inputDomicilio" value="{{ alumno.domicilio }}" required>
              </div>
            </div>


            </br>


            <div class="form-group row">
              <label for="inputCarrera" class="col-sm-2 col-form-label">Carrera:</label>
              <div class="col-sm-8">
                <select class="custom-select" id="inputCarrera" name="inputCarrera" required>
                  {% for carrera in carreras %}
                  <option value="{{ carrera.nombre_carrera }}" {% if alumno.carrera == carrera.nombre_carrera %}selected{% endif %}>{{ carrera.nombre_carrera }}</option>
                  {% endfor %}
                </select>
              </div>
            </div>


            </br>


            <div class="form-group row">
              <label for="inputRepresentante" class="col-sm-2 col-form-label">Representante Legal o Apoderado:</label>
              <div class="col-sm-8">
                <input type="text" class="form-control" id="inputRepresentante" name="inputRepresentante" value="{{ alumno.representante_legal }}">
              </div>
            </div>

            </br>


            <div class="form-group row">
              <label for="inputPrevision" class="col-sm-2 col-form-label">Prevision:</label>
              <div class="col-sm-8">
                <select class="custom-select" id="inputPrevision" name="inputPrevision" required>
                  {% if not alumno.prevision %}
                  <option value="" selected hidden>Elegir prevision...</option>
                  {% endif %}
                  {% for prevision in previsiones %}
                  <option value="{{ prevision.nombre_prevision }}" {% if alumno.prevision == prevision.nombre_prevision %}selected{% endif %}>{{ prevision.nombre_prevision }}</option>
                  {% endfor %}
                </select>
              </div>
            </div>

            </br>

            <div class="form-group row">
              <label for="inputNombreSocial" class="col-sm-2 col-form-label">Nombre Social:</label>
              <div class="col-sm-6">
                <input type="text" class="form-control" id="inputNombreSocial" name="inputNombreSocial" value="{{ alumno.nombre_social }}" placeholder="(Opcional)">
              </div>
            </div>

            </br>
            </br>

            <div class="row">
              <div class="col-md-3 ml-md-auto">
                <button id="botonGuardar" type="submit" class="btn btn-primary">Guardar</button>
              </div>
              <div class="col-md-3 ml-md-auto">
                <a href="{% url 'alumnos:verAlumno' id_alumno=alumno.id %}" role="button" class="btn btn-secondary">Atrás</a>
              </div>
            </div>

          </form>
        </div>
      </div>
    </div>
  </div>

  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    // trimear formulario (borrar espacios y tabulados antes y despes del texto)
    $(function() {
      $('input[type="text"]').change(function() {
        this.value = $.trim(this.value);
      });
    });
  </script>


  {% endblock content %}

fichaube/main/templates/editar_Area.html
{% extends 'home.html' %}


{% block content %}

<div class="col-sm-12 col-sm-offset-1">
  <div class="header text-center">
    <h2>Editar Área</h2>
  </div>
</div>

{% if messages %}
{% for message in messages %}
{% if  message.tags == "error" %}
<div class="alert alert-danger" role="alert">
  {% else %}
  <div class="alert alert-success" role="alert">
    {% endif %}
    {{message}}
  </div>
  {% endfor %}
  {% endif %}

  <div class="col-sm-12 col-sm-offset-1">
    <div class="card">
      <div class="card-content">


        <div class="cuadro-form">
          <form id="formularioNuevoNombreArea" action={% url 'areas:editarArea' %} method="post"> {% csrf_token %}
            <div class="form-group row">
              <label for="nuevoNombreArea" class="col-sm-2 col-form-label">Nuevo Nombre del Área:</label>
              <div class="col-sm-6">
                <input id="nuevoNombreArea" type="text" class="form-control"  name="nuevoNombreArea" placeholder="Nombre del Área" required>
                <input type="hidden" id="idArea" type="number" name="idArea" value={{ idArea }}>
              </div>
            </div>
            <div class="row">
              <div class="col-md-3 ml-md-auto">
                <input class="btn btn-primary"type="submit" value="Registrar">
              </div>
              <div class="col-md-3 ml-md-auto"></div>
            </div>
          </form>




          <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
          {% block javascript %}
            <script>

            // trimear formulario (borrar espacios y tabulados antes y despes del texto)
            $(function(){
              $('input[type="text"]').change(function(){
                  this.value = $.trim(this.value);
              });
            });

            //  validar formulario
            $('#formularioNuevoNombreArea').submit(function(e){
              e.preventDefault();
              var form = this;
              var area = $('#nuevoNombreArea').val();

              $.ajax({
                url: 'ajax/validarArea',
                data: {
                  'area': area
                },
                dataType: 'json',
                success: function (data) {
                  if (data.is_taken){
                    alert('El Area ingresada ya se encuentra registrada');
                    return false;
                  }
                  else{
                    form.submit();
                  }
                }
              });
            });

            </script>
          {% endblock %}

        </div>
      </div>
    </div>
  </div>

  {% endblock content %}

fichaube/main/templates/home.html
{% load staticfiles %}
{% load static %}
{% load auth_extras %}

<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <link rel="icon" type="image/png" href="{% static 'fichaube/imagen/favicon.png' %}">
  <title>Fichaube</title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />


  <!-- Bootstrap CSS CDN -->
  <!--<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">-->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <!-- Our Custom CSS -->
  <link rel="stylesheet" href="{% static 'fichaube/css/home-style.css' %}">
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="{% static 'fichaube/font-awesome/css/font-awesome.min.css' %}">
  <!-- Material -->
  <link type="text/css" href="{% static 'fichaube/js/librerias/turbo/assets/vendors/material-design-iconic-font/dist/css/material-design-iconic-font.css' %}" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{% static 'fichaube/js/librerias/turbo/assets/css/css.css' %}" />
  <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/gh/loadingio/ldbutton@v1.0.1/dist/ldbtn.min.css"/>
  <!-- MDBootstrap Datatables  -->
  <!--<link rel="stylesheet" href="{% static 'fichaube/mdbootstrap/css/addons/datatables.min.css' %}">-->

</head>

<body>

  <div class="wrapper">
    <!-- Sidebar Holder -->
    <nav id="sidebar">
      <div class="sidebar-header">
        <div class="logo">
          <a href="{% url 'home' %}" class="simple-text">
            <img src="{% static 'fichaube/imagen/logo-fichaube.png' %}" class="img-responsive" alt="Responsive image">
          </a>
        </div>
      </div>
      {% if user.is_authenticated %}
      <center><p>¡<b>Hola</b>, {{ user.get_full_name }}!</p></center>
      {% endif %}
      <ul class="list-unstyled components">
        <li class="divider"></li>
        {% if request.user|has_group:"Coordinador" or request.user|has_group:"Administrativo" or request.user|has_group:"Profesional" or request.user|has_group:"Asistente Social" or request.user.is_superuser %}
        <li>
          <a href="#fichasSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Fichas</a>
          <ul class="collapse list-unstyled show" id="fichasSubmenu">
            <li>
              <a href="{% url 'alumnos:buscarAlumno' %}">Buscar estudiante</a>
            </li>
            {% if request.user|has_group:"Coordinador" or request.user|has_group:"Administrativo" or request.user.is_superuser %}
            <li>
              <a href="{% url 'fichas:crearFicha' %}">Crear nueva ficha</a>
            </li>
            <li>
              <a href="{% url 'alumnos:crear_alumno' %}">Agregar estudiante</a>
            </li>
            {% endif %}
          </ul>
        </li>
        {% endif %}
        {% if request.user|has_group:"Coordinador" or request.user|has_group:"Administrativo" or request.user.is_superuser %}
        <li>
          <a href="#reporteSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Reportes</a>
          <ul class="collapse list-unstyled show" id="reporteSubmenu">
            <li>
              <a href="{% url 'fichas:reportes' %}">Generar reporte fichas</a>
            </li>
          </ul>
        </li>
        {% endif %}
        {% if request.user|has_group:"Coordinador" or request.user|has_group:"Administrativo" or request.user|has_group:"Mantenedor" or request.user.is_superuser %}
        <li>
          <a href="#mantenedorSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Administración</a>
          <ul class="collapse list-unstyled show" id="mantenedorSubmenu">
            {% if request.user|has_group:"Coordinador" or request.user|has_group:"Administrativo" or request.user.is_superuser%}
            <li>
              <a href="{% url 'usuarios:buscarUsuario' %}">Buscar usuarios</a>
            </li>
            <li>
              <a href="{% url 'usuarios:crear_usuario' %}">Agregar usuarios</a>
            </li>
            {% if request.user|has_group:"Coordinador" or request.user.is_superuser%}
            <li>
              <a href="{% url 'areas:lista_Areas' %}">Áreas</a>
            </li>
            <li>
              <a href="{% url 'areas:agregar_Area' %}">Crear Área</a>
            </li>
            {% endif %}
            {% endif %}
            <li>
              <a href="{% url 'alumnos:importAlumnos' %}">Cargar estudiantes</a>
            </li>
          </ul>
        </li>
        {% endif %}
        <li>
          <a href="#cuentaSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Cuenta</a>
          <ul class="collapse list-unstyled show" id="cuentaSubmenu">
            <li>
              <a href="{% url 'usuarios:cambiarPass' %}">Cambiar contraseña</a>
            </li>
          </ul>
        </li>
      </ul>
      <div class="navbar-header">
        <center>
          <img src="{% static 'fichaube/imagen/dae-PUCV.png' %}" class="img-responsive" alt="Responsive image" width="150">
        </center>
      </div>
    </nav>

    <!-- Page Content Holder -->
    <div id="content">

      <nav id="navegador-superior" class="navbar navbar-expand-lg bg" id="cabecera">
        <div class="container-fluid">

          <button type="button" id="sidebarCollapse" class="navbar-btn">
            <span></span>
            <span></span>
            <span></span>
          </button>


          <div class="row">
            <div class="col-md-4 ml-sm-auto" id="cerrarSesion">
              <a href="{% url 'logout' %}" style="font-weight:50; color:#ffff;">
                <i class="zmdi zmdi-sign-in" style="font-size:25px; color:#ffff;"></i>Cerrar Sesion
              </a>
            </div>
            <div class="col-md-2 ml-sm-auto"></div>
          </div>


        </div>
      </nav>

      <div class="container-fluid d-flex flex-column">

        {% block content %}

        {% if messages %}
        {% for message in messages %}
        {% if  message.tags == "error" %}
        <div class="alert alert-danger" role="alert">
          {% else %}
          <div class="alert alert-success" role="alert">
            {% endif %}
            {{message}}
          </div>
          {% endfor %}
          {% endif %}

          <div class="jumbotron">
            <h1>¡Bienvenido! </h1>
            </br>
          </div>
          {% endblock %}

        </div>

        <div class="line"></div>

      </div>
    </div>

    <!-- jQuery CDN - Slim version (=without AJAX) -->
          <!-- ESTA ES LA VERSION SLIM DE JQUERY
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
          -->
          <!-- VERSION FULL DE JQUERY -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <!--<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>-->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <!-- MDBootstrap Datatables  -->
    <!--<script type="text/javascript" src="{% static 'fichaube/mdbootstrap/js/addons/datatables.min.js' %}"></script>-->

    <script type="text/javascript" src="{% static 'fichaube/js/validarut.js' %}"></script>
    <script type="text/javascript" src="{% static 'fichaube/js/validapass.js' %}"></script>
    <script type="text/javascript" src="{% static 'fichaube/js/activadorRutPasaporte.js' %}"></script>
    <script type="text/javascript" src="{% static 'fichaube/js/activadorAreaEspecialidad.js' %}"></script>
    <script type="text/javascript" src="{% static 'fichaube/js/sorttable.js' %}"></script>

    <!-- SCRIPT COMPORTAMIENTO SIDEBAR -->
    <script type="text/javascript">
      $(document).ready(function() {
        $('#sidebarCollapse').on('click', function() {
          $('#sidebar').toggleClass('active');
          $(this).toggleClass('active');
        });

        $('li > a').click(function() {
          $('li').removeClass('active');
          $(this).parent().addClass('active');
        });

        $('a[href$="#modalDelete"]').on("click", function() {
          $('#modalDelete').modal('show');
        });

        $('a[rel$="popover"]').popover();

      });
    </script>

    <!-- SCRIPT FILTRO TABLAS -->
    <script>
      $(document).ready(function() {
        $("#filtroTabla").on("keyup", function() {
          var value = $(this).val().toLowerCase();
          $("#tablaBusqueda tr").filter(function() {
            $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
          });
        });
      });
    </script>

</body>

</html>

fichaube/main/templates/reportes.html
{% extends 'home.html' %}
{% block content %}

<div class="col-sm-12 col-sm-offset-1">
  <div class="header text-center">
    <h2>Generación de Reportes</h2>
  </div>
</div>

{% if messages %}
{% for message in messages %}
{% if  message.tags == "error" %}
<div class="alert alert-danger" role="alert">
  {% else %}
  <div class="alert alert-success" role="alert">
    {% endif %}
    {{message}}
  </div>
  {% endfor %}
  {% endif %}

  <div class="col-sm-12 col-sm-offset-1">
    <div class="card">
      <div class="card-content">
        <div class="cuadro-tabla">
          <div class="form-group">
            <label for="exampleInputFile">Descargar reporte de fichas clínicas:</label>
            <a id="generarReporte" type="button" name="generarReporte" class="btn btn-primary" href="{% url 'fichas:generarReporte' %}">Descargar</a>
            <small id="emailHelp" class="form-text text-muted">
              Se descargará un archivo .xlsx que contiene los estudiantes que poseen una ficha clínica, y el total de estos.</small>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
   <script>
     // $('#generarReporte').click(function(){
    //   $.ajax({
    //     url: 'ajax/generarReporte',
    //     success: function(response){
    //       return true;     }
    //});
   //});
   </script>


  {% endblock content %}

fichaube/main/templates/testpancho.html
<html>
  <body>
    <form action="agregarArea" method="post"> {% csrf_token %}
      {{ form.as_p }}
      <label for="area">Ingrese area: </label>
      <br>
      <input id="area" type="text" name="area">
      <input type="submit" value="Submit">
    </form>
  </body>
</html>